In [1]:
import numpy as np
import h5py

In [9]:
# 测试文件 arrayTest.txt 是 a[5][2][3][3] 
array = np.loadtxt("D:/arrayTest.txt",dtype = 'int32', delimiter=" ",usecols = range(3))

In [10]:
array  

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39],
       [40, 41, 42],
       [43, 44, 45],
       [46, 47, 48],
       [49, 50, 51],
       [52, 53, 54],
       [55, 56, 57],
       [58, 59, 60],
       [61, 62, 63],
       [64, 65, 66],
       [67, 68, 69],
       [70, 71, 72],
       [73, 74, 75],
       [76, 77, 78],
       [79, 80, 81],
       [82, 83, 84],
       [85, 86, 87],
       [88, 89, 90]])

In [17]:
realData = array.reshape(5,2,3,3)  # 维度转换成我们的维度

In [18]:
realData

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]],


       [[[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]],

        [[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]]],


       [[[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]]],


       [[[55, 56, 57],
         [58, 59, 60],
         [61, 62, 63]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]]],


       [[[73, 74, 75],
         [76, 77, 78],
         [79, 80, 81]],

        [[82, 83, 84],
         [85, 86, 87],
         [88, 89, 90]]]])

In [19]:
with h5py.File('realArray.h5') as f:  # 写 h5 文件
    f.create_dataset("data", data = realData)

In [20]:
fr = h5py.File('realArray.h5','r')  # 读 h5 文件
myData = fr['data'].value

In [21]:
myData

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]],


       [[[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]],

        [[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]]],


       [[[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]]],


       [[[55, 56, 57],
         [58, 59, 60],
         [61, 62, 63]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]]],


       [[[73, 74, 75],
         [76, 77, 78],
         [79, 80, 81]],

        [[82, 83, 84],
         [85, 86, 87],
         [88, 89, 90]]]])